Update MeasUI for SampleMeasurement and update Default Value for Double2DArray in measurement and relevant tests
ni/measurement-plugin-python pull request #1034
Opened 2024-12-12 12:40 UTC by Blahpapto1

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-plugin-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

TODO: Include high-level description of the changes in this pull request.

### Why should this Pull Request be merged?

TODO: Justify why this contribution should be part of the project.

### What testing has been done?

TODO: Detail what testing has been done to ensure this submission meets requirements.

2024-12-12 21:51 UTC, dixonjoel approved these changes

2024-12-16 17:10 UTC, bkeryan requested changes

2024-12-16 17:10 UTC, bkeryan commented on packages/service/ni_measurement_plugin_sdk_service/measurement/service.py
> +                "DataType.Double2DArray is not supported for configuration parameters."
That's not the only unsupported configuration data type, is it?
```suggestion
        if type in [DataType.Double2DArray, DataType.DoubleXYData, DataType.DoubleXYData1D]:
            raise ValueError(
                f"{type} is not supported for configuration parameters."
```

2024-12-16 17:10 UTC, bkeryan commented on examples/sample_measurement/SampleAllParameters.measui
> Update MeasUI and Default Value for Double2DArray for SampleMeasurement and relevant tests. Also, block Double2DArray Input as configuration parameter. 

Please write concise PR titles and 1st-line-of-commit-messages.

e.g. `service: Disallow message configurations, update sample measurement accordingly`

2024-12-16 17:12 UTC, bkeryan commented on examples/sample_measurement/SampleAllParameters.measui
> 
![image](https://github.com/user-attachments/assets/939a099b-a40b-46e1-907b-6c6aa49b7372)

Why is the new output-only parameter under the in/out parameters? It would make more sense to put it under the graph.

Do 2D arrays support graphs?

2024-12-17 09:26 UTC, Blahpapto1 commented on examples/sample_measurement/SampleAllParameters.measui
Updated PR Title. Will keep in mind about commit messages.

2024-12-17 09:27 UTC, Blahpapto1 commented on examples/sample_measurement/SampleAllParameters.measui
Updated `.measui`, moving the Double2DArray Output control under the graph.

2024-12-17 18:08 UTC, bkeryan approved these changes

2024-12-18 07:58 UTC, merged