Add enumerate services API
ni/measurement-plugin-python pull request #826
Opened 2024-08-02 08:16 UTC by Jotheeswaran-Nandagopal

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implementation of the enumerate service API, which return the active measurement services
- Added automation test

### Why should this Pull Request be merged?

- This implementation supports the Interactive Approach for the [Measurement Plug-In client API](https://dev.azure.com/ni/DevCentral/_git/ASW?path=/Specs/Test%20Automation%20Frameworks/E2719769_Support%20for%20Measurement%20Plug-In%20client%20APIs/E2719769_Support%20for%20Measurement%20Plug-In%20client%20APIs.md&version=GBmain&_a=preview&anchor=interactive-approach)'s in python 

### What testing has been done?

Existing and new automated tests passed.

2024-08-02 10:02 UTC, jayaseelan-james commented on packages/service/tests/unit/test_discovery_client.py
> +def test___active_measurements_available___enumerate_services___returns_list_of_measurements(
```suggestion
def test___registered_measurements___enumerate_services___returns_list_of_measurements(
```

2024-08-02 10:02 UTC, jayaseelan-james commented on packages/service/tests/unit/test_discovery_client.py
> +    EnumerateServicesResponse,
nit: These should be placed above the RegisterServiceRequest following the alphabetical order.

2024-08-02 11:53 UTC, Jotheeswaran-Nandagopal commented on packages/service/tests/unit/test_discovery_client.py
> +        available_services=[register_service_request.service_description]
I referred the `test___service_registered___unregister_service_no_args___sends_request_and_returns_true` test, where they registered the service and then unregistered. So, followed the same to get the service description from the registered services.

2024-08-02 13:37 UTC, Jotheeswaran-Nandagopal commented on packages/service/tests/unit/test_discovery_client.py
> +        available_services=[register_service_request.service_description]
Updated the logic for mocking by using the test values.

2024-08-02 15:00 UTC, bkeryan requested changes

2024-08-05 12:51 UTC, dixonjoel approved these changes

2024-08-05 16:18 UTC, bkeryan approved these changes
Approved with suggestion

2024-08-06 04:21 UTC, jayaseelan-james approved these changes

2024-08-06 04:21 UTC, jayaseelan-james commented on packages/service/tests/unit/test_discovery_client.py
> +    grpc_service_descriptor = GrpcServiceDescriptor(
Can we consider renaming this to something as `expected_service` or `expected_available_service` or `enumerate_services_response`?

2024-08-06 06:16 UTC, SowmyaRavee approved these changes

2024-08-06 06:32 UTC, merged